### MemberAdress Create
POST http://localhost:8080/addresses
Content-Type: application/json
X-MEMBER-ID: 1

{
  "name" : "변상우2",
  "phoneNumber" : "010-0000-0000",
  "alias" : "우리집",
  "requestedTerm" : "급하게 빨리 와주세요~",
  "zipCode" : "999-999",
  "roadNameAddress" : "광주광역시 팔문대로24555342",
  "numberAddress" : "광주광역시 동구 동명동 113-9823321",
  "notes" : "(동명동)",
  "detailAddress" : "999호",
  "defaultLocation" : 0
}

### MemberAddress Read (by addressId)
GET http://localhost:8080/addresses/2
Content-Type: application/json
X-MEMBER-ID: 1

### MemberAddress Read (by memberId)
GET http://localhost:8080/addresses
Content-Type: application/json
X-MEMBER-ID: 1

### MemberAddress Update
PUT http://localhost:8080/addresses
Content-Type: application/json
X-MEMBER-ID: 1

{
  "id" : 52,
  "name" : "aaa",
  "phoneNumber" : "010-0000-0000",
  "alias" : "aaa",
  "requestedTerm" : "aaa",
  "zipCode" : "999-999",
  "roadNameAddress" : "aaa",
  "numberAddress" : "aaa",
  "notes" : "aaa",
  "detailAddress" : "aaa",
  "defaultLocation" : 0
}


### MemberAdress Delete
DELETE http://localhost:8080/addresses
Content-Type: application/json
X-MEMBER-ID: 1

{
  "id" : 352
}



